#!/bin/bash

docker run -it -p 5002:5002 --name mozilla synesthesiam/mozillatts:en
apt update -y
apt install vim -y
apt install rsync -y
apt install wget -y
apt-get install --reinstall ca-certificates
mkdir /usr/local/share/ca-certificates/cacert.org
wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt
update-ca-certificates
git config --global http.sslCAinfo /etc/ssl/certs/ca-certificates.crt
git clone https://github.com/mrkeyboard44/chatbot-coqui.git
rsync -av chatbot-coqui/ tts_web/
